<template>
  <div class="grid grid-cols-12 gap-5 px-5 flex w-full pb-32">
    <div
      v-for="(slide, key) in slides"
      :key="key"
      class="col-span-12 fade-in"
      :class="[cols[key], align[key], pad[key]]"
    >
      <ImageAsset :image="slide.fields.images[0]" />
    </div>
  </div>
</template>
<script>
import ImageAsset from "@/components/ImageAsset";
import _ from "lodash";
export default {
  components: {
    ImageAsset,
  },
  props: ["slides"],
  data() {
    return {
      cols: [
        "sm:col-span-6 delay-one",
        "sm:col-span-3 delay-two",
        "sm:col-span-3 delay-three",
      ],
      align: ["sm:self-start", "sm:self-center", "sm:self-end"],
      pad: ["sm:py-5", "sm:py-10", "sm:py-12"],
    };
  },
  mounted() {
    this.cols = _.shuffle(this.cols);
    this.align = _.shuffle(this.align);
    this.pad = _.shuffle(this.pad);
  },
};
</script>
<style scoped>
.delay-one {
  animation-delay: 0ms !important;
}
.delay-two {
  animation-delay: 0.5s !important;
}
.delay-three {
  animation-delay: 1s !important;
}
.fade-in {
  -webkit-animation: fade-in 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-2 2:0:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
