<template>
  <div
    class="grid grid-cols-12 gap-5 px-5 flex w-full pb-32 bg-gray-100 relative"
  >
    <div
      v-for="(slide, key) in slides"
      :key="key"
      class="fade-in"
      :class="[cols[key], align[key], pad[key]]"
    >
      <ImageAsset
        @mouseover="
          selectedKey = key;
          hover = true;
        "
        @mouseout="hover = false"
        style="max-height: 50vh"
        :image="slide.fields.images[0]"
      />
    </div>
    <div class="absolute w-full text-left bottom-5 left-5">
      <router-link to="/collection" class="flex items-center">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke-width="1.5"
          stroke="currentColor"
          class="w-4 h-4 mr-2"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3"
          />
        </svg>
        View Our Collection
      </router-link>
    </div>
  </div>
</template>
<script>
import ImageAsset from "@/components/ImageAsset";
import _ from "lodash";
export default {
  components: {
    ImageAsset,
  },
  props: ["slides"],
  data() {
    return {
      hover: false,
      selectedKey: 0,
      cols: [
        "col-span-6 delay-one",
        "col-span-3 delay-two",
        "col-span-3 delay-three",
      ],
      align: ["self-start", "self-center", "self-end"],
      pad: ["py-5", "py-10", "py-12"],
    };
  },
  mounted() {
    this.cols = _.shuffle(this.cols);
    this.align = _.shuffle(this.align);
    this.pad = _.shuffle(this.pad);
  },
  computed: {
    title() {
      return _.get(this.slides[this.selectedKey], "fields.title");
    },
    artist() {
      return _.get(this.slides[this.selectedKey], "fields.artist");
    },
    year() {
      return _.get(this.slides[this.selectedKey], "fields.year");
    },
  },
};
</script>
<style scoped>
.delay-one {
  animation-delay: 0ms !important;
}
.delay-two {
  animation-delay: 0.5s !important;
}
.delay-three {
  animation-delay: 1s !important;
}
.fade-in {
  -webkit-animation: fade-in 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in 0.5s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2022-10-2 2:0:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in
 * ----------------------------------------
 */
@-webkit-keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
@keyframes fade-in {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
